name: NukkitCloudnetNPC
main: NukkitCloudnetNPC.Main

version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: Guillaume351
description: Cookie Build NPC system


commands:
  joinmb:
    description: Join a Microbattles game
    usage: "/joinmb"
    permission: nnpc.account.basic
  joinbb:
    description: Join a BuildBattle game
    usage: "/joinbb"
    permission: nnpc.account.basic
  joinsw:
    description: Join a SkyWars game
    usage: "/joinsw"
    permission: nnpc.account.basic


permissions:
  nnpc.account.basic:
    description: "Allow the user to /pos"
    default: true